"use client";

import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell,
  LabelList,
} from "recharts";
import { InfoIcon } from "lucide-react";

interface PulseSectionProps {
  globalAverage: number;
  data: {
    promptsTested: number;
    modelVisibility: {
      model: string;
      value: number;
      isAverage?: boolean;
    }[];
  };
}

export default function PulseSection({
  data,
  globalAverage,
}: PulseSectionProps) {
  const { modelVisibility } = data;
  // Sort data by value in descending order, but keep Global Avg at the end
  const sortedData = [...modelVisibility].sort((a, b) => b.value - a.value);

  // Prepare chart data
  const chartData = sortedData.map((item) => ({
    name: item.model,
    value: item.value,
  }));

  return (
    <div className="mb-16 bg-white rounded-xl border border-gray-200 shadow-sm overflow-hidden">
      <div className="px-6 py-5 border-b border-gray-100 bg-gray-50">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-gray-900">
              Pulse — Brand Visibility
            </h2>
            <p className="text-sm text-gray-600 mt-1">
              The percentage of times your brand is mentioned by AI when asked
              about your industry.
            </p>
          </div>
          <a
            href="/glossary"
            className="text-gray-400 hover:text-primary transition-colors"
          >
            <InfoIcon className="h-5 w-5" />
          </a>
        </div>
      </div>

      <div className="p-6">
        <div className="mb-8">
          <div className="flex flex-col md:flex-row md:justify-between md:items-end gap-4 mb-6">
            <div>
              <div className="flex items-center mb-1">
                <h3 className="text-3xl font-bold text-gray-900">
                  {globalAverage}%
                </h3>
                <span className="ml-2 px-2 py-1 text-xs font-medium bg-blue-100 text-blue-800 rounded-full">
                  Global Average
                </span>
              </div>
            </div>
            <div className="text-right">
              <div className="text-sm font-medium text-gray-900">
                Prompts Tested
              </div>
              <div className="text-2xl font-bold text-gray-900">
                {data.promptsTested}
              </div>
            </div>
          </div>
        </div>

        {/* Afficher directement les détails sans bouton */}
        <div className="mb-6">
          <h4 className="text-lg font-semibold text-gray-800 mb-4">
            Model Breakdown
          </h4>
          <div className="h-80">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart
                data={chartData}
                layout="vertical"
                margin={{ top: 5, right: 30, left: 20, bottom: 5 }}
              >
                <CartesianGrid
                  strokeDasharray="3 3"
                  horizontal={true}
                  vertical={false}
                />
                <XAxis
                  type="number"
                  domain={[0, 100]}
                  tickFormatter={(value) => `${value}%`}
                />
                <YAxis
                  type="category"
                  dataKey="name"
                  width={120}
                  tick={{ fill: "#374151", fontWeight: 500 }}
                />
                <Tooltip
                  formatter={(value) => [`${value}%`, "Visibility"]}
                  labelFormatter={(label) => `Model: ${label}`}
                  contentStyle={{
                    backgroundColor: "white",
                    border: "1px solid #e5e7eb",
                    borderRadius: "0.375rem",
                    boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
                  }}
                />
                <Bar dataKey="value" radius={[0, 4, 4, 0]} barSize={30}>
                  {chartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill="#3182CE" />
                  ))}
                  <LabelList
                    dataKey="value"
                    position="right"
                    formatter={(value: any) => `${value}%`}
                    style={{
                      fill: "#111827",
                      fontWeight: 600,
                      fontSize: 14,
                    }}
                  />
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="border-t border-gray-100 pt-6">
          <h4 className="text-lg font-semibold text-gray-800 mb-4">
            What is Pulse Score?
          </h4>
          <p className="text-gray-600 mb-4">
            Pulse score (%) = Total mention rate of your brand across all
            responses generated by AI models when asked about your industry or
            product category.
          </p>
          <div className="bg-blue-50 border border-blue-100 rounded-lg p-4">
            <div className="flex items-start">
              <a href="/glossary" className="flex-shrink-0 mt-0.5">
                <InfoIcon className="h-5 w-5 text-blue-500 hover:text-blue-700 transition-colors" />
              </a>
              <div className="ml-3">
                <h5 className="text-sm font-medium text-blue-800">
                  Methodology
                </h5>
                <ul className="mt-1 text-sm text-blue-700 list-disc pl-5 space-y-1">
                  <li>Unique prompts tested = {data.promptsTested}</li>
                  {/* <li>Sequences run = 3</li> */}
                  <li>
                    Total "Pulse" responses generated by model ={" "}
                    {data.promptsTested * modelVisibility.length}
                  </li>
                  {/* <li>225 responses across all models tested</li> */}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
