version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/brand_insights?schema=public
      - NODE_ENV=development
      - PORT=3000
      - BATCH_ENABLED=true
      - SPONT_PROMPTS=12
      - DIRECT_PROMPTS=12
      - COMP_PROMPTS=8
      - CONCURRENCY_LIMIT=5
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=brand_insights
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: