version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run start:dev"
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/geo
      - NODE_ENV=development
      - PORT=3000
      - BATCH_ENABLED=true
      - SPONT_PROMPTS=12
      - DIRECT_PROMPTS=12
      - COMP_PROMPTS=8
      - CONCURRENCY_LIMIT=5
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    ports:
      - "27027:27017"
    environment:
      - MONGO_INITDB_DATABASE=geo
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: